# Generated by Django 6.0.2 on 2026-02-19 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Time when the record was created.', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Time when the record was last updated.', verbose_name='updated at')),
                ('predicted_gpa', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='predicted GPA')),
                ('risk_level', models.CharField(choices=[('LOW', 'Low Risk'), ('MEDIUM', 'Medium Risk'), ('HIGH', 'High Risk')], default='LOW', max_length=20, verbose_name='risk level')),
                ('risk_score', models.DecimalField(decimal_places=4, help_text='Probability of failure/dropout (0-1)', max_digits=5, verbose_name='risk score')),
                ('prediction_date', models.DateField(auto_now_add=True)),
                ('model_version', models.CharField(default='v1.0', max_length=50)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='academics.student')),
            ],
            options={
                'get_latest_by': 'created_at',
                'indexes': [models.Index(fields=['student', 'risk_level'], name='student_risk_idx'), models.Index(fields=['risk_level'], name='risk_level_lookup_idx')],
            },
        ),
    ]
