# Generated by Django 6.0.2 on 2026-02-19 10:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0002_initial'),
        ('attendance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='classsession',
            name='created_by',
            field=models.ForeignKey(help_text='Teacher who created this session', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='classsession',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='academics.subject'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='class_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='attendance.classsession'),
        ),
        migrations.AddIndex(
            model_name='classsession',
            index=models.Index(fields=['subject', 'date'], name='session_lookup_idx'),
        ),
        migrations.AddConstraint(
            model_name='classsession',
            constraint=models.UniqueConstraint(fields=('subject', 'date'), name='unique_session_per_subject_date'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['class_session', 'status'], name='attendance_status_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['student', 'status'], name='student_attendance_idx'),
        ),
        migrations.AddConstraint(
            model_name='attendance',
            constraint=models.UniqueConstraint(fields=('class_session', 'student'), name='unique_attendance_per_session'),
        ),
    ]
