# Generated by Django 5.2.14 on 2026-07-09 05:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0012_teacher_department'),
        ('attendance', '0005_attendance_deleted_at_attendance_is_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='college',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='academics.college'),
        ),
        migrations.AddField(
            model_name='classsession',
            name='college',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='academics.college'),
        ),
    ]
