# Generated by Django 5.2.14 on 2026-07-09 05:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0012_teacher_department'),
        ('attendance', '0006_attendance_college_classsession_college'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='college',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.college'),
        ),
        migrations.AlterField(
            model_name='classsession',
            name='college',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.college'),
        ),
    ]
