# Generated by Django 5.2.11 on 2026-06-28 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('placements', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='jobapplication',
            options={'ordering': ['-applied_at']},
        ),
        migrations.AlterModelOptions(
            name='jobposting',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='jobskill',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='studentskill',
            options={'ordering': ['id']},
        ),
    ]
