databases:
  - name: spms_db
    databaseName: spms_db
    user: spms_user

services:
  - type: web
    name: spms-backend
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn config.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: spms_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: ".onrender.com,localhost"
      - key: CORS_ALLOWED_ORIGINS
        value: "*" # Ensure you change this to your Vercel URL later
      - key: DEBUG
        value: "False"
      - key: PYTHON_VERSION
        value: "3.11.0"
