# Generated by Django 6.0.2 on 2026-02-19 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Time when the record was created.', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Time when the record was last updated.', verbose_name='updated at')),
                ('name', models.CharField(max_length=100, verbose_name='assessment name')),
                ('assessment_type', models.CharField(choices=[('INTERNAL_1', 'Internal Test 1'), ('INTERNAL_2', 'Internal Test 2'), ('INTERNAL_3', 'Internal Test 3'), ('INTERNAL_4', 'Internal Test 4'), ('SEMESTER', 'Semester Exam'), ('QUIZ', 'Weekly Quiz')], default='QUIZ', max_length=20, verbose_name='type')),
                ('max_marks', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='max marks')),
                ('weightage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='weightage %')),
                ('date', models.DateField(verbose_name='assessment date')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Time when the record was created.', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Time when the record was last updated.', verbose_name='updated at')),
                ('marks_obtained', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='marks obtained')),
                ('remarks', models.CharField(blank=True, max_length=255, verbose_name='remarks')),
            ],
        ),
    ]
