# Generated by Django 6.0.2 on 2026-02-19 10:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0002_initial'),
        ('assessments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assessment',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='academics.subject'),
        ),
        migrations.AddField(
            model_name='marks',
            name='assessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='assessments.assessment'),
        ),
        migrations.AddField(
            model_name='marks',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='academics.student'),
        ),
        migrations.AddConstraint(
            model_name='assessment',
            constraint=models.UniqueConstraint(fields=('subject', 'name', 'date'), name='unique_assessment_per_subject'),
        ),
        migrations.AddIndex(
            model_name='marks',
            index=models.Index(fields=['assessment', 'marks_obtained'], name='assessment_marks_idx'),
        ),
        migrations.AddIndex(
            model_name='marks',
            index=models.Index(fields=['student', 'assessment'], name='student_marks_lookup_idx'),
        ),
        migrations.AddConstraint(
            model_name='marks',
            constraint=models.UniqueConstraint(fields=('assessment', 'student'), name='unique_marks_per_assessment'),
        ),
    ]
