# Generated by Django 5.2.14 on 2026-06-03 15:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0008_alter_subject_unique_together_alter_batch_id_and_more'),
        ('assessments', '0004_alter_assessment_id_alter_marks_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Time when the record was created.', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Time when the record was last updated.', verbose_name='updated at')),
                ('title', models.CharField(max_length=150, verbose_name='title')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('file', models.FileField(blank=True, null=True, upload_to='assignments/briefs/', verbose_name='assignment file')),
                ('due_date', models.DateTimeField(verbose_name='due date')),
                ('max_marks', models.DecimalField(decimal_places=2, default=100.0, max_digits=5, verbose_name='max marks')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_tasks', to='academics.subject')),
            ],
            options={
                'ordering': ['-due_date'],
            },
        ),
        migrations.CreateModel(
            name='AssignmentSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Time when the record was created.', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Time when the record was last updated.', verbose_name='updated at')),
                ('file', models.FileField(upload_to='assignments/submissions/', verbose_name='submission file')),
                ('marks_obtained', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='marks obtained')),
                ('remarks', models.TextField(blank=True, verbose_name='remarks')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_submissions', to='academics.student')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='assessments.assignmenttask')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='assignmenttask',
            constraint=models.UniqueConstraint(fields=('subject', 'title'), name='unique_assignment_task_per_subject'),
        ),
        migrations.AddConstraint(
            model_name='assignmentsubmission',
            constraint=models.UniqueConstraint(fields=('assignment', 'student'), name='unique_submission_per_assignment'),
        ),
    ]
