# Generated by Django 5.2.14 on 2026-07-09 05:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0012_teacher_department'),
        ('assessments', '0006_assessment_deleted_at_assessment_is_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='college',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='academics.college'),
        ),
        migrations.AddField(
            model_name='assignmentsubmission',
            name='college',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='academics.college'),
        ),
        migrations.AddField(
            model_name='assignmenttask',
            name='college',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='academics.college'),
        ),
        migrations.AddField(
            model_name='marks',
            name='college',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='academics.college'),
        ),
    ]
