# Generated by Django 5.2.14 on 2026-07-09 05:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0012_teacher_department'),
        ('assessments', '0007_assessment_college_assignmentsubmission_college_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='college',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.college'),
        ),
        migrations.AlterField(
            model_name='assignmentsubmission',
            name='college',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.college'),
        ),
        migrations.AlterField(
            model_name='assignmenttask',
            name='college',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.college'),
        ),
        migrations.AlterField(
            model_name='marks',
            name='college',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.college'),
        ),
    ]
