# Generated by Django 6.0.2 on 2026-02-20 08:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_resource'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='batch_year',
            field=models.IntegerField(blank=True, null=True, verbose_name='batch year'),
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Time when the record was created.', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Time when the record was last updated.', verbose_name='updated at')),
                ('name', models.CharField(max_length=50, verbose_name='batch name')),
                ('year', models.IntegerField(verbose_name='start year')),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='academics.college')),
            ],
            options={
                'ordering': ['-year'],
                'constraints': [models.UniqueConstraint(fields=('college', 'year'), name='unique_batch_per_college')],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Time when the record was created.', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Time when the record was last updated.', verbose_name='updated at')),
                ('name', models.CharField(max_length=100, verbose_name='department name')),
                ('code', models.CharField(max_length=20, verbose_name='department code')),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='academics.college')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('college', 'code'), name='unique_dept_code_per_college')],
            },
        ),
    ]
