# Generated by Django 6.0.2 on 2026-02-20 08:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_remove_student_batch_year_student_batch_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='department',
            name='unique_dept_code_per_college',
        ),
        migrations.AddField(
            model_name='department',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='academics.batch'),
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['batch'], name='dept_batch_idx'),
        ),
        migrations.AddConstraint(
            model_name='department',
            constraint=models.UniqueConstraint(fields=('college', 'batch', 'code'), name='unique_dept_code_per_batch'),
        ),
    ]
