# Generated by Django 5.2.14 on 2026-07-05 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0010_batch_deleted_at_batch_is_deleted_college_deleted_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='department',
        ),
        migrations.AddField(
            model_name='teacher',
            name='department_name',
            field=models.CharField(blank=True, help_text='Kept for backward compatibility with existing data.', max_length=100, verbose_name='department name (legacy)'),
        ),
        migrations.AlterField(
            model_name='college',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='contact email'),
        ),
        migrations.AlterField(
            model_name='college',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='contact phone'),
        ),
    ]
