# Generated by Django 5.2.14 on 2026-07-05 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0011_remove_teacher_department_teacher_department_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='department',
            field=models.ForeignKey(blank=True, help_text='Department this teacher belongs to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teachers', to='academics.department'),
        ),
    ]
